const test = require('node:test');
const assert = require('node:assert/strict');
const {
    isMacScreenshotName,
    sanitizeForFilename,
    buildOutputFilename,
    processScreenshot
} = require('../server');

test('detects supported macOS screenshot prefixes', () => {
    assert.equal(isMacScreenshotName('Screenshot 2026-05-27 at 8.04.05 PM.png'), true);
    assert.equal(isMacScreenshotName('Screen Shot 2026-05-27 at 8.04.05 PM.png'), true);
    assert.equal(isMacScreenshotName('IMG_1001.png'), false);
});

test('sanitizes AI summary to filename-safe format', () => {
    assert.equal(sanitizeForFilename('Flexbox layout BUG!!!'), 'flexbox-layout-bug');
    assert.equal(sanitizeForFilename('api-call-timeout---retry'), 'api-call-timeout-retry');
    assert.equal(sanitizeForFilename('--ok--'), 'ok');
});

test('builds output filename with app, branch, and summary', () => {
    const name = buildOutputFilename('Visual Studio Code', 'main', 'render-bug', '.png');
    assert.equal(name, 'visual-studio-code-main-render-bug.png');
});

test('processScreenshot runs rename and tag flow with injected dependencies', async () => {
    const calls = {
        renamed: null,
        tagged: null
    };

    await processScreenshot('/tmp/Screenshot 2026-05-27 at 8.04.05 PM.png', {
        getActiveWindowInfo: () => ({ appName: 'Cursor', windowTitle: 'screenshot-genius' }),
        getGitBranch: () => 'main',
        analyzeImageWithOllama: async () => 'test-summary',
        renameSync: (from, to) => {
            calls.renamed = { from, to };
        },
        addTags: (filePath, tags) => {
            calls.tagged = { filePath, tags };
        }
    });

    assert.deepEqual(calls.renamed, {
        from: '/tmp/Screenshot 2026-05-27 at 8.04.05 PM.png',
        to: '/tmp/cursor-main-test-summary.png'
    });
    assert.deepEqual(calls.tagged, {
        filePath: '/tmp/cursor-main-test-summary.png',
        tags: 'Cursor,test-summary,AutoGenerated'
    });
});
